// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbrclpovvhcdtkiygokh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFicmNscG92dmhjZHRraXlnb2toIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwOTEyMDIsImV4cCI6MjA3NjY2NzIwMn0.tb-cOhfAJSAgX9ldPyC7KHs5R6dE6-hs7WtzPCkHZco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});